import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function generateReportPDF(
  prediction,
  user = null
) {
  const doc = new jsPDF();

  let y = 18;

  // ==========================
  // Header
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("MediVerse", 105, y, {
    align: "center",
  });

  y += 8;

  doc.setFontSize(13);
  doc.setTextColor(80);

  doc.text(
    "AI Health Analysis Report",
    105,
    y,
    {
      align: "center",
    }
  );

  y += 12;

  doc.setDrawColor(220);
  doc.line(15, y, 195, y);

  y += 10;

  // ==========================
  // Patient Information
  // ==========================

  doc.setFontSize(11);
  doc.setTextColor(0);

  doc.text(
    `Patient : ${user?.name || "Unknown User"}`,
    15,
    y
  );

  y += 7;

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    15,
    y
  );

  y += 12;

  // ==========================
  // Matched Symptoms
  // ==========================

  doc.setFontSize(14);
  doc.setTextColor(37, 99, 235);

  doc.text("Matched Symptoms", 15, y);

  y += 6;

  autoTable(doc, {
    startY: y,

    head: [
      [
        "Input",
        "Matched",
        "Confidence",
      ],
    ],

    body:
      prediction.matched_symptoms.map(
        (item) => [
          item.input,
          item.matched,
          `${(
            item.score * 100
          ).toFixed(1)} %`,
        ]
      ),
  });

  y = doc.lastAutoTable.finalY + 12;

  // ==========================
  // Diseases
  // ==========================

  prediction.predictions.forEach(
    (disease, index) => {

      if (y > 240) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(16);
      doc.setTextColor(37, 99, 235);

      doc.text(
        `${index + 1}. ${disease.disease.replaceAll(
          "_",
          " "
        )}`,
        15,
        y
      );

      y += 7;

      doc.setFontSize(11);
      doc.setTextColor(0);

      doc.text(
        `Severity : ${disease.severity}`,
        15,
        y
      );

      y += 8;

      doc.setFont("helvetica", "bold");

      doc.text("Summary", 15, y);

      y += 6;

      doc.setFont("helvetica", "normal");

      const summary =
        doc.splitTextToSize(
          disease.summary,
          180
        );

      doc.text(summary, 15, y);

      y += summary.length * 6 + 4;

      // Medicines

      doc.setFont(
        "helvetica",
        "bold"
      );

      doc.text(
        "Recommended Medicines",
        15,
        y
      );

      y += 6;

      doc.setFont(
        "helvetica",
        "normal"
      );

      disease.recommended_medicines.forEach(
        (medicine) => {

          doc.text(
            `• ${medicine}`,
            20,
            y
          );

          y += 6;

        }
      );

      y += 3;

      // Precautions

      doc.setFont(
        "helvetica",
        "bold"
      );

      doc.text(
        "Precautions",
        15,
        y
      );

      y += 6;

      doc.setFont(
        "helvetica",
        "normal"
      );

      disease.precautions.forEach(
        (item) => {

          doc.text(
            `• ${item}`,
            20,
            y
          );

          y += 6;

        }
      );

      y += 3;

      doc.setFont(
        "helvetica",
        "bold"
      );

      doc.text(
        "Recommended Specialist",
        15,
        y
      );

      y += 6;

      doc.setFont(
        "helvetica",
        "normal"
      );

      doc.text(
        disease.doctor_speciality,
        20,
        y
      );

      y += 12;

    }
  );

  // ==========================
  // Disclaimer
  // ==========================

  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(220);

  doc.line(15, y, 195, y);

  y += 10;

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.text(
    "Disclaimer",
    15,
    y
  );

  y += 8;

  doc.setFont(
    "helvetica",
    "normal"
  );

  const disclaimer =
    prediction.predictions[0]
      ?.disclaimer ||
    "This report is generated by AI and is intended for informational purposes only.";

  const text =
    doc.splitTextToSize(
      disclaimer,
      180
    );

  doc.text(text, 15, y);

  y += text.length * 6 + 8;

  doc.setTextColor(120);

  doc.text(
    "Generated by MediVerse AI",
    105,
    y,
    {
      align: "center",
    }
  );

  doc.save("MediVerse_Report.pdf");
}